### ISSUE TITLE
Integrate MeiliSearch

### ISSUE THREAD

**Issue by m2chan** [Open-Sourced-Olaf/Get-svg-icons#5]
Integrate super fast and efficient MeiliSearch into our icon search feature.

**Comment by steven-tey** [comment]
After a couple of trial and errors, I decided not to implement Meilisearch because it's overkill for a small project like ours (it's better for JSON files with >100,000 entries)

Instead, I added a feature where if a user's search query matches one of the tags in the description, the icon shows up:


https://user-images.githubusercontent.com/28986134/109065278-33277180-76a0-11eb-918c-805e876b151f.mov
